# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 15:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='00', max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('pays', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=30)),
                ('code_postal', models.CharField(max_length=30)),
                ('rubrique', models.CharField(choices=[('FAMILLE', 'Famille'), ('MAISON', 'Maison'), ('SANTE', 'Sante'), ('TRAVAIL', 'Travail'), ('LOISIRS', 'Loisirs')], max_length=30)),
                ('titre_annonce', models.CharField(max_length=100)),
                ('descriptif_annonce', models.TextField()),
                ('date_depot', models.DateTimeField(default=datetime.datetime(2016, 12, 31, 16, 12, 49, 498100))),
                ('pris_en_charge', models.BooleanField(default=False)),
                ('lundi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='00', max_length=30)),
                ('mardi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='00', max_length=30)),
                ('mercredi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='00', max_length=30)),
                ('jeudi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='00', max_length=30)),
                ('vendredi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='00', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialiste', models.CharField(choices=[('FAMILLE', 'Famille'), ('MAISON', 'Maison'), ('SANTE', 'Sante'), ('TRAVAIL', 'Travail'), ('LOISIRS', 'Loisirs')], max_length=30)),
                ('coach_image', models.CharField(default='img', max_length=1000)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=20)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librecoach.Coach'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
