# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0003_auto_20161231_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='coach_rubrique',
            new_name='rubrique',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 31, 20, 19, 37, 280552)),
        ),
    ]
