# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('pays', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=30)),
                ('code_postal', models.IntegerField()),
                ('rubrique', models.CharField(max_length=30)),
                ('titre_annonce', models.CharField(max_length=100)),
                ('descriptif_annonce', models.TextField()),
                ('disponibilité', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_coach', models.CharField(max_length=30)),
                ('prenom_coach', models.CharField(max_length=30)),
                ('specialiste', models.CharField(max_length=20)),
                ('demande_rdv', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticket',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='annonce',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librecoach.Coach'),
        ),
    ]
