# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0002_auto_20161221_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='annonce',
        ),
        migrations.AddField(
            model_name='coach',
            name='annonce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='librecoach.Annonce'),
            preserve_default=False,
        ),
    ]
