# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0006_auto_20161223_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='disponibilité',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
