# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 15:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 31, 16, 14, 24, 310901)),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(default='inconnu', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
