# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0002_auto_20161231_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='coach',
            new_name='coach_rubrique',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='rubrique',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 31, 20, 15, 5, 218389)),
        ),
    ]
