# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0012_auto_20161223_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 21, 45, 15, 296046)),
        ),
    ]
