# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0015_auto_20161224_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 29, 18, 53, 15, 140717)),
        ),
        migrations.AlterField(
            model_name='coach',
            name='specialiste',
            field=models.CharField(choices=[('FAMILLE', 'Famille'), ('MAISON', 'Maison'), ('SANTE', 'Sante'), ('TRAVAIL', 'Travail'), ('LOISIRS', 'Loisirs')], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='librecoach.Coach'),
        ),
    ]
