# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0017_auto_20161229_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='coach',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 29, 19, 1, 45, 682513)),
        ),
    ]
