# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0003_auto_20161221_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='rubrique',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=30),
        ),
    ]
