# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0004_auto_20161223_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='code_postal',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='rubrique',
            field=models.CharField(choices=[('FAMILLE', 'famille'), ('MAISON', 'Maison'), ('SANTE', 'Sante'), ('TRAVAIL', 'Travail'), ('LOISIRS', 'Loisirs')], max_length=30),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
