# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librecoach', '0005_auto_20161223_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='pris_en_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='disponibilité',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='rubrique',
            field=models.CharField(choices=[('FAMILLE', 'Famille'), ('MAISON', 'Maison'), ('SANTE', 'Sante'), ('TRAVAIL', 'Travail'), ('LOISIRS', 'Loisirs')], max_length=30),
        ),
    ]
