# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 17:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librecoach', '0008_auto_20161223_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lundi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA JOURNEE', 'la journee')], max_length=30)),
                ('mardi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA JOURNEE', 'la journee')], max_length=30)),
                ('mercredi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA JOURNEE', 'la journee')], max_length=30)),
                ('jeudi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA JOURNEE', 'la journee')], max_length=30)),
                ('vendredi', models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA JOURNEE', 'la journee')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='disponibilité',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='annonce',
        ),
        migrations.AddField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 18, 15, 16, 613725)),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librecoach.Annonce'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
