# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 18:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librecoach', '0011_auto_20161223_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='jeudi',
            field=models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='---------', max_length=30),
        ),
        migrations.AddField(
            model_name='annonce',
            name='lundi',
            field=models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='---------', max_length=30),
        ),
        migrations.AddField(
            model_name='annonce',
            name='mardi',
            field=models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='---------', max_length=30),
        ),
        migrations.AddField(
            model_name='annonce',
            name='mercredi',
            field=models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='---------', max_length=30),
        ),
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='vendredi',
            field=models.CharField(choices=[('INDISPONIBLE', 'indisponible'), ('MATIN', 'matin'), ('APRES-MIDI', 'apres-midi'), ('LA_JOURNEE', 'la_journee')], default='---------', max_length=30),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_depot',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 23, 19, 25, 7, 112362)),
        ),
    ]
